"""Engagement ports -- the six universal bounded engagement families (Section 2).

This is the v2 core. An `EngagementPort` is the numerical geometric annotation of
ONE way a real 3-D part can engage other annotated geometry. There are exactly six
families; they are NUMERICAL FORMS, not catalog part classes. A catalog part emits
several ports (a pulley = cylindrical bore receiver + periodic rotary teeth + hub
planar faces). Catalog-family names like `timing_pulley` live in `semantic_aliases`
and NEVER drive geometric acceptance (Hard Rule 4 / Section 3).

Strict geometry, permissive policy: annotate as strongly as evidence allows; a
known contradiction fails, missing data is `unknown`/`partial`, never silently
incompatible. Required fields per family are validated on construction -- the v1
"giant untyped params bag" is rejected (migration step A.3).

All geometry is millimetres in the part's immutable local frame.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .primitives import Axis, Plane, Path, Interval, Polygon2D, LocalFrame

FAMILIES = {
    "cylindrical",    # shafts, bores, journals, pins, races, collars, round rails
    "planar",         # mounting seats, bearing faces, flanges, clamp jaws
    "swept_profile",  # T-slots, dovetails, keyways, captured tracks, guide rails
    "threaded",       # internal/external machine threads
    "periodic",       # timing/gear teeth, splines, sprockets, toothed clamp regions
    "flexible_path",  # belts, chains, cables, routed flexible elements
}

# allowed polarity values per family (Section 2)
_POLARITY = {
    "cylindrical": {"insert", "receiver"},
    "planar": {"contact"},
    "swept_profile": {"insert", "receiver"},
    "threaded": {"internal", "external"},
    "periodic": {"external", "internal", "opposing"},
    "flexible_path": {"routed"},
}

ANNOTATION_STATUS = {"confirmed", "nominal", "inferred", "partial", "unknown", "contradicted"}


@dataclass
class EngagementPort:
    """A bounded attachment affordance (Section 3). `geometry` is the family-specific
    required numerical contract (validated below). Acceptance is generated by
    family + polarity + numerical predicates -- never by `semantic_aliases`."""
    id: str
    family: str
    polarity: str
    geometry: dict                          # family-specific, validated in _check
    access: dict = field(default_factory=dict)            # insertion/removal dirs
    symmetry: dict = field(default_factory=dict)
    semantic_aliases: list = field(default_factory=list)  # search/display ONLY
    evidence_refs: list = field(default_factory=list)
    annotation_status: str = "nominal"
    unknowns: list = field(default_factory=list)

    def __post_init__(self):
        if self.family not in FAMILIES:
            raise ValueError(f"port {self.id}: family {self.family!r} not in {sorted(FAMILIES)}")
        if self.polarity not in _POLARITY[self.family]:
            raise ValueError(f"port {self.id}: polarity {self.polarity!r} invalid for "
                             f"{self.family} (allowed {sorted(_POLARITY[self.family])})")
        if self.annotation_status not in ANNOTATION_STATUS:
            raise ValueError(f"port {self.id}: bad annotation_status {self.annotation_status!r}")
        _CHECKERS[self.family](self)

    # ---- convenience accessors used by the family matchers --------------------
    def axis(self) -> Axis:
        g = self.geometry["axis"]
        return Axis(origin=tuple(g["origin"]), direction=tuple(g["direction"]))

    def radial_interval(self) -> Interval:
        return Interval.from_json(self.geometry["radial_interval_mm"])

    def axial_interval(self) -> Interval:
        return Interval.from_json(self.geometry["axial_interval_mm"])

    def to_json(self) -> dict:
        return {
            "id": self.id, "family": self.family, "polarity": self.polarity,
            "geometry": self.geometry, "access": self.access, "symmetry": self.symmetry,
            "semantic_aliases": list(self.semantic_aliases),
            "evidence_refs": list(self.evidence_refs),
            "annotation_status": self.annotation_status, "unknowns": list(self.unknowns),
        }

    @staticmethod
    def from_json(d: dict) -> "EngagementPort":
        return EngagementPort(
            id=d["id"], family=d["family"], polarity=d["polarity"],
            geometry=d["geometry"], access=d.get("access", {}),
            symmetry=d.get("symmetry", {}), semantic_aliases=d.get("semantic_aliases", []),
            evidence_refs=d.get("evidence_refs", []),
            annotation_status=d.get("annotation_status", "nominal"),
            unknowns=d.get("unknowns", []),
        )


# ---- per-family required-field validation (strict; Section 2) -----------------

def _need(port: EngagementPort, *keys):
    for k in keys:
        if k not in port.geometry:
            raise ValueError(f"port {port.id} ({port.family}): missing required "
                             f"geometry field {k!r}")


def _check_axis(g, pid):
    a = g.get("axis")
    if not (isinstance(a, dict) and "origin" in a and "direction" in a):
        raise ValueError(f"port {pid}: axis must be {{origin, direction}}")


def _check_cylindrical(p):
    _need(p, "axis", "radial_interval_mm", "axial_interval_mm", "material_side")
    _check_axis(p.geometry, p.id)
    if p.geometry["material_side"] not in ("inside", "outside"):
        raise ValueError(f"port {p.id}: cylindrical material_side must be inside|outside")
    p.radial_interval(); p.axial_interval()        # validate intervals


def _check_planar(p):
    _need(p, "plane", "boundary_uv_mm", "material_side")
    pl = p.geometry["plane"]
    if not ("origin" in pl and "normal" in pl):
        raise ValueError(f"port {p.id}: plane must be {{origin, normal}}")
    if p.geometry["material_side"] not in ("positive_normal", "negative_normal"):
        raise ValueError(f"port {p.id}: planar material_side must be positive_normal|negative_normal")


def _check_swept(p):
    _need(p, "sweep_path", "sweep_interval_mm", "section_frame",
          "section_profile_uv_mm", "material_side")
    if p.geometry["material_side"] not in ("inside_profile", "outside_profile"):
        raise ValueError(f"port {p.id}: swept material_side must be inside_profile|outside_profile")
    Interval.from_json(p.geometry["sweep_interval_mm"])


def _check_threaded(p):
    _need(p, "axis", "axial_interval_mm", "thread")
    _check_axis(p.geometry, p.id)
    th = p.geometry["thread"]
    for k in ("standard", "pitch_mm", "handedness"):
        if k not in th:
            raise ValueError(f"port {p.id}: threaded.thread missing {k!r}")


def _check_periodic(p):
    _need(p, "support", "periodicity", "profile")
    if p.geometry.get("subtype") not in ("rotary", "linear"):
        raise ValueError(f"port {p.id}: periodic subtype must be rotary|linear")
    if "pitch_mm" not in p.geometry["periodicity"]:
        raise ValueError(f"port {p.id}: periodic.periodicity missing pitch_mm")


def _check_flexible(p):
    _need(p, "center_path", "width_mm")
    Interval.from_json(p.geometry["width_mm"])


_CHECKERS = {
    "cylindrical": _check_cylindrical,
    "planar": _check_planar,
    "swept_profile": _check_swept,
    "threaded": _check_threaded,
    "periodic": _check_periodic,
    "flexible_path": _check_flexible,
}


# ---- PortGroup: an exact composition (bolt pattern, paired faces) -- Section 4 -

@dataclass
class PortGroup:
    """A first-class exact relationship among ports (a bolt pattern, a paired
    bearing-face set, a continuous placement domain). NOT a new engagement family;
    pattern matching solves correspondence subject to declared symmetry."""
    id: str
    kind: str                               # repeated_ports | composite_port | continuous_domain
    members: list = field(default_factory=list)   # [{"port": id, "transform": {...}}]
    frame: dict | None = None
    symmetry: dict = field(default_factory=dict)
    placement_domain: dict | None = None
    evidence_refs: list = field(default_factory=list)

    def __post_init__(self):
        if self.kind not in ("repeated_ports", "composite_port", "continuous_domain"):
            raise ValueError(f"port_group {self.id}: bad kind {self.kind!r}")

    def to_json(self) -> dict:
        return {"id": self.id, "kind": self.kind, "members": self.members,
                "frame": self.frame, "symmetry": self.symmetry,
                "placement_domain": self.placement_domain,
                "evidence_refs": list(self.evidence_refs)}

    @staticmethod
    def from_json(d: dict) -> "PortGroup":
        return PortGroup(id=d["id"], kind=d["kind"], members=d.get("members", []),
                         frame=d.get("frame"), symmetry=d.get("symmetry", {}),
                         placement_domain=d.get("placement_domain"),
                         evidence_refs=d.get("evidence_refs", []))
